name: rim-genie

services:
  postgres:
    image: postgres
    container_name: rim-genie-postgres
    environment:
      POSTGRES_DB: rim-genie
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5439:5432"
    volumes:
      - rim-genie_postgres_data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

volumes:
  rim-genie_postgres_data:
